// Script to populate author fields in books.json
const fs = require('fs');

const authorMap = {
        '巨人思維': '巨人傑',
        '底層邏輯 I': '劉潤',
        '華頓商學院最受歡迎的談判課': 'Stuart Diamond',
        '目標': 'Eliyahu M. Goldratt',
        '刻意練習': 'Anders Ericsson',
        '定位': 'Al Ries, Jack Trout',
        '時勢': '張忠謀',
        '留白時間': 'Juliet Funt',
        '情緒靈敏力': 'Susan David',
        '底層邏輯2 Underlaying Logic 2': '劉潤',
        '精準選股 7Nothing': '陳喬泓',
        '軟技能': 'John Sonmez',
        '散漫者的學習法': '佐佐木俊尚',
        '你不欠任何人': 'Emily P. Freeman',
        'Nexus': 'Yuval Noah Harari',
        '哈佛寫作課': 'Steven Pinker',
        '高效寫作': '鄭緯筌',
        '寫作是最好的自我投資': '陳立飛',
        '可複製的溝通力': '樊登',
        '低風險創業': '樊登',
        '聖經教你的18個修煉秘訣': '施以諾',
        '一如既往': 'Morgan Housel',
        '丹尼爾斯博士跑步方程式': 'Jack Daniels',
        '跑步教科書': '牧野仁',
        '改善體質深呼吸': 'Patrick McKeown',
        '身為之體動具一揭面紗': '比爾・乾尼漢',
        '財務自由之路 享來來': '博多・舍費爾',
        '價值': '張磊',
        '投資幫幫忙': '何文碩',
        '來賓斯的投資哲學': '霍華・乾克斯',
        '殺到': '李尚龍',
        '窮查理的普通常識': 'Charlie Munger',
        '管理含的實語常識': '凱因斯',
        '認識商業': 'William Nickels',
        '心流': 'Mihaly Csikszentmihalyi',
        '學習究竟是什麼': '安德斯・乾里克森',
        '學習到的學習': '芭芭拉・奧克利',
        '大人的學習法': '和田秀樹',
        'Satir 的對話練習': '李崇建',
        '最高學習法': '石井裕之',
        '成長型領導': 'Carol S. Dweck',
        '為什麼事情做不完 你還在滑手機': '吳淡如',
        '刷新好的孤獨': '薩提亞・乾德拉',
        '原子習慣': 'James Clear',
        '與成功有約': 'Stephen R. Covey',
        '第八個習慣 The 8th': 'Stephen R. Covey',
        '先問為什麼': 'Simon Sinek',
        '納瓦爾寶典': 'Eric Jorgenson',
        '從0到1 Zero to One  Notes on Startups, or': 'Peter Thiel',
        '稻盛和夫 中小企業學': '稻盛和夫',
        '人類大歷史': 'Yuval Noah Harari',
        '打開心智': '萬維鋼',
        '六頂思考帽': 'Edward de Bono',
        '深度工作力': 'Cal Newport',
        '超速學習': 'Scott H. Young',
        '複利效應': 'Darren Hardy',
        '極度專注力': 'Chris Bailey',
        '聚焦一件事': 'Gary Keller',
        '清單革命': 'Atul Gawande',
        '金錢心理學': 'Morgan Housel',
        '兆元教練': 'Eric Schmidt',
        '領導最後吃': 'Simon Sinek',
        '無限賽局': 'Simon Sinek',
        '逆思維': 'Adam Grant',
        '隱性潛能': 'Adam Grant',
        '給予': 'Adam Grant',
        '藍海策略': 'W. Chan Kim',
        '打造第二大腦': 'Tiago Forte',
        '高成效習慣': 'Brendon Burchard',
        '持續買進': 'Nick Maggiulli',
        '僕人領導': 'James C. Hunter',
        '噪音 判斷的偏差': 'Daniel Kahneman',
        '可預測的不理性': 'Dan Ariely',
        '誰說人是誠實的': 'Dan Ariely',
        '簡單致富': 'JL Collins',
        '勇於領導': 'Brené Brown',
        '人生四千個禮拜': 'Oliver Burkeman',
        '快樂假設': 'Jonathan Haidt',
        '習慣的力量': 'Charles Duhigg',
        '創意公司': 'Ed Catmull',
        '創意自信': 'David Kelley, Tom Kelley',
        '清晰思考的藝術': 'Rolf Dobelli',
        '人生勝利聖經': 'Tim Ferriss',
        '巴菲特寫給股東的信': 'Warren Buffett',
        '巴菲特勝券在握的12個原則': 'Robert Hagstrom',
        '人性賽局': 'Robert Wright',
        '千腦智能理論': 'Jeff Hawkins',
        '人類的旅程': 'Oded Galor',
        '2100 科技大未來': 'Michio Kaku',
        '細胞之歌': 'Siddhartha Mukherjee',
        '為什麼要睡覺': 'Matthew Walker',
        '天生就會跑': 'Christopher McDougall',
        '麥凱銷售聖經': 'Harvey Mackay',
        '誘惑的藝術': 'Robert Greene',
        '強大內心的自我對話習慣': 'Ethan Kross',
        '把時間買回來': 'Dan Martell',
        '決策的藝術': 'John S. Hammond',
        '情緒跟你以為的不一樣': 'Lisa Feldman Barrett',
        '會講故事的大腦': 'Werner Siefer',
        '意識究竟從何而來': 'Michael Graziano',
        '呼喊訊號  混亂': 'Tim Harford',
        '創造與漫想': 'Jeff Bezos',
        '21 Lessons for the 21st Century by Yuval Noah Harari': 'Yuval Noah Harari',
        '絕不妥協': 'Chris Voss',
        '步步為贏': 'Mark Batterson',
        '專注力協定': 'Nir Eyal',
        '說理': 'Jay Heinrichs',
        '好與壞的策略': 'Richard Rumelt',
        '高道領導': 'John C. Maxwell',
        '新一分鐘管理': 'Ken Blanchard',
        '勾引大腦 Story or Die How to Use Brain Science to Engage^J Persuade^J and': 'Lisa Cron',
        '重啟人生': 'Arthur C. Brooks',
        '思辯賽局': 'Avinash Dixit',
        '怦然心動的人生整理魔法': '近藤麻理惠',
        '系統思考': 'Donella Meadows',
        '不服從的藝術': '中島聰',
        '真實的快樂': 'Martin Seligman',
        '多巴胺排毒': 'Anna Lembke',
        '破框思維的技術': '狩野未希',
        '超速進步': 'Daniel Coyle',
        '假性親密關係': '百合子',
        '喜樂之書': 'Dalai Lama, Desmond Tutu',
        '供應鏈戰爭': 'Chris Miller',
        '亞馬遜逆向工作法 Working Backwards Insights, Stories, and': 'Colin Bryar',
        '鬆綁你的焦慮習慣': 'Judson Brewer',
        '10% Happier - Taming the Voice in My Head': 'Dan Harris',
        '如何讓人改變想法': 'David McRaney',
        '增長的邏輯': '李善友',
        '薩提爾的親密關係修復練習': '李崇建',
        '策略思考的六項訓練': '嶋田毅',
        '擁抱同理心': 'Daniel Goleman',
        '斯多葛主義小書': 'Jonas Salzgeber',
        '100 Ways to Motivate Yourself': 'Steve Chandler',
        '億萬富翁的成功習慣 Millionaire Success Habits The Gateway to Wealth ^0': 'Dean Graziosi',
        '有錢人與你的差距 不只是錢': '咪蒙',
        '3 Minute Positivity Journal - Boost Your Mood^J Change Your Life': 'Kristen Butler',
        '我想跟你好好聊聊': '李松蔚',
        '幸福之路': 'Bertrand Russell',
        '隱喻領導力': '陳朝益',
        '什麼都不教的上司才厲害': '森泰造',
        '盲視效應 Blind Sight   Matt Johnson PhD,': 'Matt Johnson',
        '你就是困住自己的那座山': 'Brianna Wiest',
        '我們攜帶的光': 'Michelle Obama',
        '改變人生的早起習慣養成   塚本亮': '塚本亮',
        '世界是平的 大腦是皺的': '謝伯讓',
        '不要變成壞掉的大人': '十方',
        '別讓自責成為一種習慣   根本裕幸': '根本裕幸',
        '停損的勝算': 'Annie Duke',
        '倦怠 為何我們不想工作   波波夫 Exhausted Why We Don\'t': '波波夫',
        '假面社交    李軒洋': '李軒洋',
        '紅人經濟   李檬': '李檬',
        '子彈溝通   言語武器化 精準吸睛法': '何亞妮',
        '總統文膽魅力表達課   江原國': '江原國',
        '晤談的力量 陳恆霖': '陳恆霖',
        '關於人生的7項財務思考   謝劍平': '謝劍平',
        '投資中最簡單的事   邱國鷺': '邱國鷺',
        '順著大腦來生活': '大衛・乾克',
        '購物心理學': 'Paco Underhill',
        '一鍵購買': 'Brad Stone',
        '規模化效應': 'Reid Hoffman',
        '多一法則': 'Ed Mylett',
        '同理心對話': 'Celeste Headlee',
        '心無止境': 'Jim Kwik',
        '智能簡史': '黃鐵軍',
        '無限起點': '李檬',
        '十倍故事力  Story 10x': 'Matthew Dicks',
        '十倍成功規則 The 10X': 'Grant Cardone',
        '別依個人進餐': 'Keith Ferrazzi',
        '明年就當百萬富翁': 'Rachel Cruze',
        '激勵為何無效': 'Susan Fowler',
        '哈佛大學的思辨溝通術': 'Jay Silverman',
        '腦力與無限公司': 'Jim Kwik',
        '與婚姻有約 The 7': 'Stephen R. Covey',
        '致勝心態': 'Carol S. Dweck',
        '起床後的黃金一小時': '池田千恵',
        '心念的力量': '許瑞云, 鄭先安',
        'Cant Hurt Me 我 刀槍不入': 'David Goggins',
        '情緒同理': 'Leslie Greenberg',
        '新斷捨離': '山下英子',
        '自律的科學': 'Peter Hollins',
        '高效時間管理': 'Kevin Kruse',
        '恐懼的禮物': 'Gavin de Becker',
        '批判性思維': 'Tom Chatfield',
        '深度思考': 'Garry Kasparov',
        '練腦求成': '茂木健一郎',
        '海權爭霸': 'James Stavridis',
        '領導者的七種原型': 'Lolly Daskal',
        '情緒食療': '吳宏乾',
        '不確定下的自在': 'Pema Chödrön',
        '向生命說 YES 兒Man\'s': 'Viktor Frankl',
        '超越恐懼的大魔法': 'Elizabeth Gilbert',
        '微小美麗的事物': 'Cheryl Strayed',
        '怎樣解題': 'George Pólya',
        '原則': 'Ray Dalio',
        '快思慢想': 'Daniel Kahneman',
        '做自己的生命設計師': 'Bill Burnett, Dave Evans',
        '拖延心理學': 'Jane Burka, Lenora Yuen',
        '自卑與超越': 'Alfred Adler',
        '重新與人對話': 'Sherry Turkle',
        '你要如何衡量你的人生': 'Clayton M. Christensen',
        '慷慨的力量': 'Adam Grant',
        '全腦人生': 'Jill Bolte Taylor',
        '像頂尖運動員一樣思考': 'Jean François Ménard',
        '財務自由之路 李笑來': '李笑來',
        '索羅斯的投資哲學': 'George Soros',
        '窮理查的普通常識': 'Charlie Munger',
        '讀懂一本書': '樊登',
        '你的善良必須更有力量': '海苔熊',
        '樂觀者的遠見': 'Bina Venkataraman',
        '做個有溫度的人': '林書煒',
        '打破大腦偽科學': 'Dean Burnett',
        '麥肯錫團隊協作力': '伊賀泰代',
        '有效決策': 'Steven Johnson',
        '大賭注心態': 'Annie Duke',
        '協作原則': 'Chris Fussell',
        '個人無限公司': '何則文',
        '過載': '鄧飛',
        '1分鐘GPS溝通術': '大須賀雅子',
        '掌控演講': 'Chris Anderson',
        '與逆境同行': '洪蘭',
        '工作原力': 'Bruce Daisley',
        '最有專注力的一年': 'Chris Bailey',
        '淤泥效應': 'Jonah Berger',
        '改善-改變命運的一小步': 'Robert Maurer',
        '折棉被吧 !': 'William H. McRaven',
        '正向的關鍵 - 舒適': 'Lachlan Brown',
        '別再脫離舒適區': 'Farrah Storr',
        '學習如何學習': 'Barbara Oakley',
        '大人的高效獨學法': '本山勝寬',
        '超強記憶學習法': 'Jim Kwik',
        '記憶訓練': 'Jim Kwik',
        '深度思考的技術': '齋藤嘉則',
        '閱讀力大全': '齋藤孝',
        '雜訊時代的高效資料整理術': '岡野純',
        '和這個世界講講道理': '萬維鋼',
        '為什麼我們總是相信自己是對的': 'Julia Galef',
        '活著覺得麻煩的人': '岡田尊司',
        '慣性思維': 'Michael McQueen',
        '我為何會這樣 - MBTI人格類型的16種性格密碼': 'Isabel Briggs Myers',
        '內心對話的力量': 'Ethan Kross',
        '決勝視角': 'Dave Asprey',
        '南計畫': 'David Allen',
        '當上主管後難道只能默默崩潰': '前田鎌利',
        '夠好的工作': 'Simone Stolzoff',
        'CIA探員教你培養高應變力的孩子': 'Christina Hillsberg',
        'CIA教你讓人說出真心話': 'Philip Houston',
        '日本頂尖執事教你察言觀色': '新井直之',
        '1秒轉換情緒的51個心理學技巧': '中村將',
        '讓世界身心失調的狂愛與恐懼之因': 'Marianne Williamson',
        '讓幸福流進來的賺錢框架': '本田健',
        '領導力聖經 Maxwell Leadership Bible  Select Insights from Genesis to 1': 'John C. Maxwell',
        '成功101 Success 101 Maxwell\'s Insights on Success  Purpose^J Growth^J and': 'John C. Maxwell',
        '親愛的股東': 'Lawrence A. Cunningham',
        '市場的預兆': 'Michael Batnick',
        '業務學': '趙正明',
        '未來駭客': '汪建均',
        '腦神精行銷學　Brain science for business ビジネスに活かす脳科学': '茂木健一郎',
        '200%的人生': '陳怡嘉',
        '內在提問': 'Byron Katie',
        '放棄的力量': 'Seth Godin',
        '練習不想要': '松浦彌太郎',
        '思考的法則': 'Edward de Bono',
        '機緣力': 'Christian Busch',
        '下一個現在': 'Lee Smolin',
        '信任的秘密': 'Stephen M.R. Covey',
        '再忙也要躺好躺滿': 'Matthew Walker',
        '勾引': 'Nir Eyal',
        '解決問題 先從盲點開始 プロの思考整理術': '齋藤嘉則',
        '魯蛇的翻轉人生計畫 凡人くんの人生革命': 'ヒトデ',
        '學會曼陀羅計畫表 你想要的都得到 一流の達成力': '原田隆史',
        '親愛的那不是你的錯': 'Mark Wolynn',
        '讓身心回歸平衡的姿勢與呼吸調整法': '片平悅子',
        '全齡顧齒攻略': '魏矜持',
        '吃藥前你必須知道的事': '王明鉅',
        '底層網紅': '王宗道',
        '譯者即叛徒': '趙彦春',
        '重新丈量世界': '安德魯‧乾克斯',
        '激活增長': '王賽',
        '無人地球': 'Alan Weisman',
        '如何跟誰都能聊': 'Leil Lowndes',
        '溝通技巧訓練': 'Dale Carnegie',
        '強化你的溝通技巧': 'Dale Carnegie',
        '有效溝通的科學': 'Dale Carnegie',
        '社會技巧引導': 'Patrick King',
        '努力卻不費力': 'Greg McKeown',
        '高情商習慣': 'Travis Bradberry',
        '寫作是最好得自我投資': '陳立飛',
        '致富察覺': 'Thomas C. Corley',
        '資訊彙整術 - YouTube 頻道主及川幸久的情報收集和表達技巧': '及川幸久',
        '真誠就是你的影響力': 'Simon Sinek',
        '同步大腦思維的時間支配術': '鈴木祐',
        '精準回饋：提升團隊績效，改善溝通的超能⼒': 'Joe Hirsch',
        '你有正確回答問題嗎': '哈爾・乾雷格森',
        '工作生活法則': '陳雪頻',
        '頂尖效能': 'Steven Kotler',
        '頂尖表現': 'Brad Stulberg',
        '用智不更用力Smarter': 'Charles Duhigg',
        '從你開始': 'Simon Sinek',
        '有果皆因': '樊登',
        '25個MBA 核心模型 25': '劉潤',
        '心智重組 Declutter Your Mind  Stop Worrying^J Relieve Anxiety^J': 'S.J. Scott',
        '內在專注力的節奏': 'Daniel Goleman',
        '專注的力量': 'Daniel Goleman',
        '專注的力量Focus': 'Daniel Goleman',
        '誰偷走了你的專注力Stolen': 'Johann Hari',
        '是誰偷了我的專注力The': 'Johann Hari',
        '頂尖領導者的行動清單': 'John C. Maxwell',
        '明天再做': 'Andrew Smart',
        '先處理困難': 'Brian Tracy',
        '心智管理非時間管理 Mind Management^J': 'David Kadavy',
        '當下工作習慣 The Now Habit at Work  Efficiency^J Balance^J and': 'Neil Fiore',
        '時間管理 Time Management  10': 'Brian Tracy',
        '完整結案': 'Jon Acuff',
        '賭注在你': 'Annie Duke',
        '哈佛商業評論 工作智慧': 'Harvard Business Review',
        '因選擇偉大': 'Jim Collins',
        '沒人真的在乎你的職涯': '坎貝爾・沃克',
        '懶惰不存在': 'Devon Price',
        '高道領導': 'John C. Maxwell',
        '發展屬於你的領導力': 'John C. Maxwell',
        '躍昇領導': 'John C. Maxwell',
        '切換你的腦袋': 'David J. Schwartz',
        '有趣習慣': 'Ingrid Fetell Lee',
        '食物心理解': 'Bee Wilson',
        '斷線': 'Cal Newport',
        '閃電醫治': 'Dale Bredesen',
        '掌控你的信仰': 'Tony Robbins',
        '掌控你的命定': 'Tony Robbins',
        '掌控你的情緒': 'Tony Robbins',
        '掌控你的學習': 'Tony Robbins',
        '掌控你的思想': 'Tony Robbins',
        '新智強度': 'Tony Robbins',
        '掌控心智圖': 'Tony Robbins',
        '留意你的心態': 'Carol S. Dweck',
        '跟愛因斯坦一起太空漫步': 'Joshua Foer',
        '心智之書': 'Daniel Kahneman',
        '代謝': 'Herman Pontzer',
        '超高效學習': 'Scott H. Young',
        '人的心': '朱光潛',
        '48小時內 都學會  How to Learn Almost Anything in 48': 'Tansel Ali',
        '不會背叛你的K書竅門': 'Barbara Oakley',
        '金字塔心智模式': 'Barbara Minto',
        '高效思考的五個要素 The 5': 'Edward B. Burger',
        '治癒': 'Jo Marchant',
        '思考之道   考え方  人生．仕事の結果が変わる': '稻盛和夫',
        '如果我的父母是控制狂': 'Lindsay C. Gibson',
        '怦然心動的人生整理魔法': '近藤麻理惠',
        'VS-35 海權爭霸': 'James Stavridis',
        'VS-20 怦然心動的人生整理魔法': '近藤麻理惠',
        'VS-19 怦然心動': '近藤麻理惠',
        'VS-18 我們為什麼會被騙': 'Maria Konnikova',
        'VS-17 系統思考': 'Donella Meadows',
        'VS-16 改變現在的你，迎向未來的你': 'Hal Hershfield',
        'VS-15 專注力協定Indistractable -': 'Nir Eyal',
        'VS-13 能量的悖論': 'Steven R. Gundry',
        'VS-11 天生不愛動': 'Daniel Lieberman',
        'VS-10 我們為何吃太多？Why': 'Andrew Jenkinson',
        'VS-09 改造新陳代謝': 'William Davis',
        'VS-08 科學減脂X瘦身全書': '仰望尾迹雲',
        'VS-07 身體': 'Bill Bryson',
        '50個級學習法 50': '柿內尚文',
        '1% 閱讀術 1%': '柳根贊',
        '讀新的藝術': 'Mortimer J. Adler',
        '內在孩童': 'Stefanie Stahl',
        '成長文化': 'Robert Kegan',
        '簡單致富': 'JL Collins',
        '明年就當百萬富翁': 'Grant Sabatier',
        '財務喜樂  FINANCIAL JOY 2 0': 'Dave Ramsey',
        '你值得致富': 'Amanda Frances',
        '協同主動領導': 'Tom Peters',
        '究竟該說什麼': 'Phil M. Jones',
        '爛數字': 'Tim Harford',
        'CEO 測試': 'Adam Bryant',
        '工作的藝術 找尋你的天職': 'Liz Forkin Bohannon',
        '關於癌症，我們是否治療太多，知道太少': 'H. Gilbert Welch',
        '從我腦出去': 'Faith G. Harper',
        '重要性評估': 'Greg McKeown',
        '時間悖論': 'Philip Zimbardo',
        '執行難點': 'Sean Covey',
        '聖經教你的18個接班秘訣': '施以諾',
};

const data = JSON.parse(fs.readFileSync('public/books.json', 'utf8'));
let updated = 0;

data.forEach(book => {
        const title = book.title_cn || book.title_en;
        if (title && authorMap[title] && !book.author) {
                book.author = authorMap[title];
                updated++;
        }
        // Also try matching with title_en
        if (!book.author && book.title_en && authorMap[book.title_en]) {
                book.author = authorMap[book.title_en];
                updated++;
        }
});

fs.writeFileSync('public/books.json', JSON.stringify(data, null, 2), 'utf8');
console.log(`Updated ${updated} books with author info out of ${data.length} total.`);
console.log('Books still without author:', data.filter(b => !b.author).length);
