const fs = require('fs');
const path = require('path');

// 1. Load Transcribed Data (from screenshots)
const transcribed = {
  "S4-01": { "en": "The Time Paradox", "author": "Philip Zimbardo" },
  "S4-02": { "en": "Do It Tomorrow", "author": "Mark Forster" },
  "S4-03": { "en": "Do the Hard Things First", "author": "Scott Allan" },
  "S4-04": { "en": "Do Hard Things", "author": "Steve Magness" },
  "S4-05": { "en": "Effective Time Management and Productivity", "author": "Tracy Weaver" },
  "S4-06": { "en": "Mind Management, Not Time Management", "author": "David Kadavy" },
  "S4-07": { "en": "The Now Habit at Work: Efficiency, Balance, and Focus", "author": "Neil Fiore" },
  "S4-08": { "en": "80/20 Your Life: Maximize Results with Minimal Effort", "author": "Damon Zahariades" },
  "S4-09": { "en": "Time Management", "author": "Geoffrey Lucas" },
  "S4-10": { "en": "Finish What You Start: The Art of Following Through", "author": "Peter Hollins" },
  "S4-11": { "en": "Betting on You", "author": "Laurie Ruettimann" },
  "S4-12": { "en": "HBR Work Smart Collection", "author": "HBR" },
  "S4-13": { "en": "Great by Choice", "author": "Jim Collins" },
  "S4-14": { "en": "Nobody Cares About Your Career", "author": "Erika Ayers Badan" },
  "S4-15": { "en": "Peak Performance", "author": "Brad Stulberg & Steve Magness" },
  "S4-16": { "en": "Peak Performance: Stress, Rest, and Sustainable Success", "author": "Fitness Academy" },
  "S4-17": { "en": "Smarter Not Harder: Biohacks for Effortless Energy and Performance", "author": "Dave Asprey" },
  "S4-18": { "en": "It Begins with You: Relationships, Patterns, and Healing", "author": "Jillian Turecki" },
  "S4-19": { "en": "The Gift of Fear", "author": "Gavin De Becker" },
  "S4-20": { "en": "Critical Thinking: The Basics of Good Reasoning", "author": "Jamie Carlin Watson" },
  "S4-21": { "en": "21 Lessons for the 21st Century", "author": "Yuval Noah Harari" },
  "S4-22": { "en": "Laziness Does Not Exist", "author": "Devon Price" },
  "S4-23": { "en": "Authentic Happiness", "author": "Martin E. P. Seligman" },
  "S4-24": { "en": "Everything Happens for a Reason", "author": "Kate Bowler" },
  "S4-25": { "en": "25 Need-to-Know MBA Models", "author": "Ken Mark" },
  "S4-26": { "en": "Never Split the Difference", "author": "Chris Voss" },
  "S4-27": { "en": "The Art of Seduction", "author": "Robert Greene" },
  "S4-28": { "en": "Limitless Mind", "author": "Jo Boaler" },
  "S4-29": { "en": "Intelligence: A Very Short Introduction", "author": "Ian J. Deary" },
  "S4-30": { "en": "Blue Ocean Strategy, Expanded Edition", "author": "W. Chan Kim" },
  "S4-31": { "en": "The Beginning of Infinity", "author": "David Deutsch" },
  "S4-32": { "en": "Building a Second Brain", "author": "Tiago Forte" },
  "S4-33": { "en": "The Achievement Habit", "author": "Bernard Roth" },
  "S4-34": { "en": "Story 10x: Turn the Impossible Into the Inevitable", "author": "Michael Margolis" },
  "S4-35": { "en": "Cultures of Growth", "author": "Mary C. Murphy" },
  "S4-36": { "en": "High Road Leadership", "author": "John C. Maxwell" },
  "S4-37": { "en": "Maxwell Leadership Bible", "author": "John C. Maxwell" },
  "S4-38": { "en": "The 10X Rule", "author": "Grant Cardone" },
  "S4-39": { "en": "Good Strategy/Bad Strategy", "author": "Richard Rumelt" },
  "S4-40": { "en": "Never Eat Alone", "author": "Keith Ferrazzi" },
  "S4-41": { "en": "The Simple Path to Wealth", "author": "JL Collins" },
  "S4-42": { "en": "Be a Millionaire Next Year", "author": "Michael R. Berg" },
  "S4-43": { "en": "Financial Joy 2.0", "author": "Sean Seah" },
  "S4-44": { "en": "Just Keep Buying", "author": "Nick Maggiulli" },
  "S4-45": { "en": "You Deserve to Be Rich", "author": "Rashad Bilal" },
  "S4-46": { "en": "The Psychology of Money", "author": "Morgan Housel" },
  "S4-47": { "en": "Why Motivating People Doesn't Work", "author": "Susan Fowler" },
  "S4-48": { "en": "Co-Active Leadership", "author": "Karen Kimsey-House" },
  "S4-49": { "en": "Exactly What to Say", "author": "Phil M Jones" },
  "S4-50": { "en": "Trillion Dollar Coach", "author": "Eric Schmidt" },
  "S4-51": { "en": "Servant Leadership", "author": "Larry W. Boone" },
  "S4-52": { "en": "Success 101", "author": "John C. Maxwell" },
  "S4-53": { "en": "Noise: A Flaw in Human Judgment", "author": "Daniel Kahneman" },
  "S4-54": { "en": "Predictably Irrational", "author": "Dan Ariely" },
  "S4-55": { "en": "Poor Numbers", "author": "Morten Jerven" },
  "S4-56": { "en": "The CEO Test", "author": "Adam Bryant" },
  "S4-57": { "en": "The Art of Work", "author": "Jeff Goins" },
  "S4-58": { "en": "The New One Minute Manager", "author": "Ken Blanchard" },
  "S4-59": { "en": "Call Sign Chaos", "author": "Jim Mattis" },
  "S4-60": { "en": "The Leap to Leader", "author": "Adam Bryant" },
  "S4-61": { "en": "Leaders Eat Last", "author": "Simon Sinek" },
  "S4-62": { "en": "Developing the Leader Within You", "author": "John C. Maxwell" },
  "S4-63": { "en": "Switch On Your Brain", "author": "Dr. Caroline Leaf" },
  "S4-64": { "en": "The Book of Joy", "author": "Dalai Lama" },
  "S4-65": { "en": "The Fun Habit", "author": "Mike Rucker" },
  "S4-66": { "en": "The Food-Mood Solution", "author": "Jack Challem" },
  "S4-67": { "en": "Lost Connections", "author": "Johann Hari" },
  "S4-68": { "en": "Lighter", "author": "Yung Pueblo" },
  "S4-69": { "en": "Get Out of My Head", "author": "Meredith Arthur" },
  "S4-70": { "en": "The Happiness Hypothesis", "author": "Jonathan Haidt" },
  "S4-71": { "en": "Master Your Beliefs", "author": "Thibaut Meurisse" },
  "S4-72": { "en": "Master Your Destiny", "author": "Thibaut Meurisse" },
  "S4-73": { "en": "Master Your Emotions", "author": "Thibaut Meurisse" },
  "S4-74": { "en": "Master Your Learning", "author": "Thibaut Meurisse" },
  "S4-75": { "en": "Master Your Thinking", "author": "Thibaut Meurisse" },
  "S4-76": { "en": "Dopamine Detox", "author": "Thibaut Meurisse" },
  "S4-77": { "en": "Mental Toughness", "author": "Annette Tower" },
  "S4-78": { "en": "Mind Map Mastery", "author": "Tony Buzan" },
  "S4-79": { "en": "Mind Your Mindset", "author": "Michael Hyatt" },
  "S4-80": { "en": "Moonwalking with Einstein", "author": "Joshua Foer" },
  "S4-81": { "en": "The Book of Minds", "author": "Philip Ball" },
  "S4-82": { "en": "Frames of Mind", "author": "Howard Gardner" },
  "S4-83": { "en": "How to Remember Anything", "author": "Dean Vaughn" },
  "S4-84": { "en": "Make It Stick", "author": "Peter C. Brown" },
  "S4-85": { "en": "Mind Magic", "author": "James R. Doty" },
  "S4-86": { "en": "Outsmart Your Brain", "author": "Daniel T. Willingham" },
  "S4-87": { "en": "The Confident Mind", "author": "Dr. Nate Zinsser" },
  "S4-88": { "en": "The Extended Mind", "author": "Annie Murphy Paul" },
  "S4-89": { "en": "The Power of Discipline", "author": "Daniel Walter" },
  "S4-90": { "en": "The Power of Fun", "author": "Catherine Price" },
  "S4-91": { "en": "The Power of Your Potential", "author": "John C. Maxwell" },
  "S4-92": { "en": "The Power of Your Subconscious Mind", "author": "Joseph Murphy" },
  "S4-93": { "en": "Quiet: The Power of Introverts", "author": "Susan Cain" },
  "S4-94": { "en": "The Art of Quiet Influence", "author": "Jocelyn Davis" },
  "S4-95": { "en": "The Secret Lives of Introverts", "author": "Jenn Granneman" },
  "S4-96": { "en": "Winning the War in Your Mind", "author": "Craig Groeschel" },
  "S4-97": { "en": "Make It Clear", "author": "Patrick Henry Winston" },
  "S4-98": { "en": "The Skill Code", "author": "Matt Beane" },
  "S4-99": { "en": "Think Like a Rocket Scientist", "author": "Ozan Varol" },
  "S4-100": { "en": "Third Millennium Thinking", "author": "Saul Perlmutter" },
  "S4-101": { "en": "The Rational Optimist", "author": "Matt Ridley" },
  "S4-102": { "en": "The Science of Self-Learning", "author": "Peter Hollins" },
  "S4-103": { "en": "The Yes Brain", "author": "Daniel J. Siegel" },
  "S4-104": { "en": "The 16 Undeniable Laws of Communication", "author": "John C. Maxwell" },
  "S4-105": { "en": "You're Not Listening", "author": "Kate Murphy" },
  "S4-106": { "en": "No Ego", "author": "Cy Wakeman" },
  "S4-107": { "en": "The Psychology of Overeating", "author": "Kima Cargill" },
  "S4-108": { "en": "Becoming Supernatural", "author": "Dr. Joe Dispenza" },
  "S4-109": { "en": "Win at Work and Succeed at Life", "author": "Michael Hyatt" },
  "S4-110": { "en": "The Ten Equations That Rule the World", "author": "David Sumpter" },
  "S4-111": { "en": "World Order", "author": "Henry Kissinger" },
  "S4-112": { "en": "Digital Empires", "author": "Anu Bradford" },
  "S4-113": { "en": "Educated", "author": "Tara Westover" },
  "S4-114": { "en": "Raising Good Humans Every Day", "author": "Hunter Clarke-Fields" },
  "S4-115": { "en": "ADHD", "author": "Paul H. Wender" },
  "S4-116": { "en": "Exploratory Writing", "author": "Alison Jones" },
  "S4-117": { "en": "Moving On Doesn't Mean Letting Go", "author": "Gina Moffa" },
  "S4-118": { "en": "No Bad Parts", "author": "Richard C. Schwartz" },
  "S4-119": { "en": "The Mindful Way through Depression", "author": "Mark Williams" },
  "S4-120": { "en": "The Perfectionist's Guide to Losing Control", "author": "Katherine Morgan Schafler" },
  "S4-121": { "en": "What Happened to You", "author": "Oprah Winfrey" },
  "S4-122": { "en": "When Bad Thinking Happens to Good People", "author": "Steven Nadler" },
  "S4-123": { "en": "This Is Strategy", "author": "Seth Godin" },
  "S4-124": { "en": "The Hidden Life of Trees", "author": "Peter Wohlleben" },
  "S4-125": { "en": "The Laws of Human Nature", "author": "Robert Greene" },
  "S4-126": { "en": "How to Work with Complicated People", "author": "Ryan Leak" },
  "S4-127": { "en": "101 Creative Problem Solving Techniques", "author": "James M. Higgins" },
  "S4-128": { "en": "No-Drama Discipline", "author": "Daniel J. Siegel" },
  "S4-129": { "en": "I Used to Have a Plan_ But Life had other Ideas", "author": "Alessandra Olanow" },
  "S4-130": { "en": "Power and Progress", "author": "Daron Acemoglu" }
};

// 2. Load YouTube Scraped Data (from earlier subagent call)
const youtubeScraped = [
  { "title": "S4 130 Power and Progress - Our Thousand-Year Struggle Over Technology and Prosperity", "videoId": "2q1zBdMPXrg" },
  { "title": "S4 129 I Used to Have a Plan but Life had other Ideas", "videoId": "6pniRv639HA" },
  { "title": "S4 128 No Drama Discipline Brain Based Strategies for Raising Compassionate Kids", "videoId": "46Hc4EVxKaA" },
  { "title": "S4 127 101 Creative Problem Solving Techniques", "videoId": "r_SCc5H7PMU" },
  { "title": "S4 126 How to Work with Complicated People", "videoId": "19Glzj_RF54" },
  { "title": "S4 125 The Laws of Human Nature", "videoId": "ia_OI5JdQnk" },
  { "title": "S4 124 The Hidden Life of Trees", "videoId": "Rka4lPm7KrU" },
  { "title": "S4 123 This Is Strategy", "videoId": "zFgfIvP_tGU" },
  { "title": "S4 122 When Bad Thinking Happens to Good People", "videoId": "Zi4AKjIWW5k" },
  { "title": "S4 121 What Happened to You Understanding Trauma and Healing", "videoId": "q8lfbLAyW7c" },
  { "title": "S4 120 The Perfectionist's Guide to Lose Control", "videoId": "-q1nksdOU2I" },
  { "title": "S4 119 The Mindful Way Through Depression", "videoId": "eBP-8BtiwPo" },
  { "title": "S4 118 No Bad Parts Healing and Transformation Through Internal Family Systems", "videoId": "ale1MCme73A" },
  { "title": "S4 117 Moving On Doesn't Mean Letting Go", "videoId": "S0s0AB_6YPM" },
  { "title": "S4 116 Exploratory Writing Everyday Magic for Life and Work", "videoId": "OMNAQJ3eOcI" },
  { "title": "S4 115 Understanding ADHD in Children and Adults", "videoId": "-iX4qBHUzkc" },
  { "title": "S4 114 Raising Good Humans Every Day", "videoId": "LkPxNXsyxTE" },
  { "title": "S4 113 Educated: A Memoir - Tara Westover", "videoId": "goWAE9gJgtY" },
  { "title": "S4 112 Digital Empires - The Global Battle to Regulate Technology", "videoId": "PG_GHakZT9I" },
  { "title": "S4 111 World Order Reflections on International Systems", "videoId": "VSyBJCU5pT8" },
  { "title": "S4 110 The Ten Equations That Rule the World", "videoId": "i6RXYlc2lwA" },
  { "title": "S4 109 Win at Work and Succeed at Life", "videoId": "xa7eaJpAAIA" },
  { "title": "S4 108 Becoming Supernatural", "videoId": "j5DrFidKko8" },
  { "title": "S4 107 The Psychology of Overeating", "videoId": "AnQXHoOZb9w" },
  { "title": "S4 106 No Ego - Bypassing Drama and Driving Workplace Accountability", "videoId": "3l2kmJvXVK4" },
  { "title": "S4 105 You're Not Listening - What You're Missing and Why It Matters", "videoId": "iXc2NYQdvMc" },
  { "title": "S4 104 The 16 Undeniable Laws of Communication", "videoId": "MW-gcuyG6mY" },
  { "title": "S4 103 The Yes Brain - How to Cultivate Courage, Curiosity, and Resilience in Your Child", "videoId": "AjmUeH48iik" },
  { "title": "S4 102 The Science of Self Learning", "videoId": "gwNE1amtcQg" },
  { "title": "S4 101 The Rational Optimist - How Prosperity Evolves", "videoId": "sha5PGjqmOI" },
  { "title": "S4 100 Third Millennium Thinking", "videoId": "ocKEpy7GiY8" },
  { "title": "S4 99 Think Like a Rocket Scientist Principles for Breakthrough Thinking", "videoId": "f7KWsvnXeJ8" },
  { "title": "S4 98 The Skill Code Mastering Skills in a Technological Age", "videoId": "To5Rwq15p6o" },
  { "title": "S4 97 Make It Clear Speak and Write to Persuade and Inform", "videoId": "hYoHh-r9WKE" },
  { "title": "S4 96 Winning the War in Your Mind", "videoId": "zgfCXErDQuU" },
  { "title": "S4 95 The Secret Lives of Introverts", "videoId": "LTvTaz_NdjM" },
  { "title": "S4 94 The Art of Quiet Influence", "videoId": "jGVJbimmM-w" },
  { "title": "S4 93 Quiet - The Power of Introverts in a World That Can't Stop Talking", "videoId": "Oidca2II0t8" },
  { "title": "S4 92 The Power of Your Subconscious Mind", "videoId": "4v_WJz5ES3o" },
  { "title": "S4 91 The Power of Your Potential", "videoId": "VC3ggWzgpJo" },
  { "title": "S4 90 The Power of Fun - Why fun is the key to a happy and healthy life", "videoId": "L63cNeCYHxQ" },
  { "title": "S4 89 The Power of Discipline How to Use Self Control and Mental Toughness to Achieve Your Goals", "videoId": "yYZXvqyhlJk" },
  { "title": "S4 88 The Extended Mind Thinking Beyond the Brain", "videoId": "wzhK4p4JonU" },
  { "title": "S4 87 The Confident Mind Effortless Performance", "videoId": "W_hGESQt60g" },
  { "title": "S4 86 Outsmart Your Brain Learning Strategies for Success", "videoId": "XLjvaJImdmk" },
  { "title": "S4 85 Mind Magic The Neuroscience of Manifesting", "videoId": "OIkwVBJZBdk" },
  { "title": "S4 84 Make It Stick The Science of Successful Learning", "videoId": "LW7Q2ERoy3o" },
  { "title": "S4 83 How to Remember Anything", "videoId": "Jz1q7iYfzME" },
  { "title": "S4 82 Frames of Mind The Theory of Multiple Intelligences", "videoId": "cGMDyQmL4us" },
  { "title": "S4 81 Book of Minds", "videoId": "wDGnUpaf7AI" },
  { "title": "S4 80 Moonwalking with Einstein The Art and Science of Remembering", "videoId": "C5OWX7wvEfs" },
  { "title": "S4 79 Mind Your Mindset Rewriting Your Brain's Stories", "videoId": "nyAvDJ1Bmyw" },
  { "title": "S4 78 Mind Map Mastery Transform Your Thinking", "videoId": "F2gtpD_xQtU" },
  { "title": "S4 77 Mental Toughness", "videoId": "LxcR5xV2dqE" },
  { "title": "S4 76 Dopamine Detox - A Short Guide to Remove Distractions and Get Your Brain to Do Hard Things", "videoId": "n24w05YVWuY" },
  { "title": "S4 75 Master Your Thinking", "videoId": "M9Ywp0Q-z7w" },
  { "title": "S4 74 Master Your Learning", "videoId": "oDKGaGNew_0" },
  { "title": "S4 73 Master Your Emotions - Overcome Negativity and Better Manage Your Feelings", "videoId": "hLsq4BYdv6A" },
  { "title": "S4 72 Master Your Destiny", "videoId": "_EmftABcSSI" },
  { "title": "S4 71 Master Your Beliefs A Practical Guide", "videoId": "_UuTBsTbSq0" },
  { "title": "S4 70 The Happiness Hypothesis - Finding Modern Truth in Ancient Wisdom", "videoId": "8X43tV2r0x8" },
  { "title": "S4 69 Get Out of My Head - Inspiration for Overthinkers in an Anxious World", "videoId": "YN9xAxa47VA" },
  { "title": "S4 68 Lighter - Let Go of the Past, Connect with the Present, and Expand The Future", "videoId": "TecILU6WwFc" },
  { "title": "S4 67 Lost Connections Uncovering the Real Causes of Depression", "videoId": "NU5rHe2V5Z0" },
  { "title": "S4 66 The Food Mood Solution", "videoId": "JQW9dhPod4g" },
  { "title": "S4 65 The Fun Habit - How the Pursuit of Joy and Wonder Can Change Your Life", "videoId": "_dAPA-HAxR0" },
  { "title": "S4 64 The Book of Joy Enduring Happiness in the Face of Suffering", "videoId": "MWZPPA-1r7A" },
  { "title": "S4 63 Switch On Your Brain - The Key to Peak Happiness, Thinking, and Health", "videoId": "1SD0a0iCikk" },
  { "title": "S4 62 Developing the Leader Within You", "videoId": "CtVfzSlT-wc" },
  { "title": "S4 61 Leaders Eat Last Human Behavior and Lasting Success", "videoId": "kfHyCRmr6oY" },
  { "title": "S4 60 The Leap to Leader Insights for Aspiring Leaders", "videoId": "Z6AZ6vpA-TU" },
  { "title": "S4 59 Call Sign Chaos Leadership and War", "videoId": "dei00urvCuk" },
  { "title": "S4 58 The New One Manager Updated Management Principles", "videoId": "qMpeqU0OEuY" },
  { "title": "S4 57 The Art of Work - Finding Your Calling", "videoId": "GY4hN1HNl6s" },
  { "title": "S4 56 The CEO Test Master Leadership's Make or Break Challenges", "videoId": "rGtSAtfYsDw" },
  { "title": "S4 55 Poor Numbers", "videoId": "Q-D9BE8QrXg" },
  { "title": "S4 54 Predictably Irrational The Hidden Forces That Shape Our Decisions", "videoId": "oWgqjRpvMro" },
  { "title": "S4 53 Noise - a Flaw in Human Judgment", "videoId": "CAFgWrxjy8Q" },
  { "title": "S4 52 Success 101: What Every Leader Should Know - John C. Maxwell", "videoId": "lJYAy3Z4WCI" },
  { "title": "S4 51 Servant Leadership by Larry W Boone", "videoId": "WWoOsejIOXY" },
  { "title": "S4 50 Trillion Dollar Coach Bill Campbell's Business Wisdom", "videoId": "gW4rkeot-As" },
  { "title": "S4 49 Exactly What to Say The Magic Words to Influence Others", "videoId": "uwL84WlXq9k" },
  { "title": "S4 48 Co-Active Leadership Powering Connection and Purpose", "videoId": "pwGUCjooz8U" },
  { "title": "S4 47 Why Motivating People Doesn't Work The New Science of Motivation", "videoId": "4B6I2qvVvnU" },
  { "title": "S4 46 The Psychology of Money", "videoId": "vv6X0eF1EKU" },
  { "title": "S4 45 You Deserve to Be Rich A Guide to Financial Freedom", "videoId": "Zj7an9ANltI" },
  { "title": "S4 44 Just Keep Buying Proven Ways to Build Your Wealth", "videoId": "PFV41c-brJ4" },
  { "title": "S4 43 FINANCIAL JOY 2 0 YOLO YOUR FINANCE", "videoId": "FZbthI2tlsA" },
  { "title": "S4 42 Be a Millionaire Next Year Smart Financial Moves", "videoId": "XTMV83cv3_w" },
  { "title": "S4 41 The Simple Path to Wealth J L Collins", "videoId": "mJPo5oOHXHc" },
  { "title": "S4 40 Never Eat Alone Secrets to Success Through Relationships", "videoId": "EszDWN39rso" },
  { "title": "S4 39 Good Strategy - Bad Strategy The Core Concepts", "videoId": "vMszbfS7n3M" },
  { "title": "S4 38 The 10X Rule Achieving Massive Action and Success", "videoId": "0E_r1jKfyDg" },
  { "title": "S4 37 Maxwell Leadership Bible Select Insights from Genesis to 1 Samuel", "videoId": "tpbXZ6RxWiU" },
  { "title": "S4 36 High Road Leadership Bringing People Together", "videoId": "xkScDuMDefw" },
  { "title": "S4 35 Cultures of Growth", "videoId": "w1yTDtO1FoY" },
  { "title": "S4 34 Story 10x - Turn the Impossible Into the Inevitable", "videoId": "Iw0U_xEa8zU" },
  { "title": "S4 33 The Achievement Habit - Stop Wishing, Start Doing, and Take Command of Your Life", "videoId": "KaEahHUZmoM" },
  { "title": "S4 32 Building a Second Brain Organize Your Digital Life", "videoId": "kGFATzA7iYA" },
  { "title": "S4 31 The Beginning of Infinity", "videoId": "A7JpyHpNeXA" },
  { "title": "S4 30 Blue Ocean Strategy Creating Uncontested Market Space", "videoId": "ViY7aRb2BbU" },
  { "title": "S4 29 Intelligence: A Very Short Introduction", "videoId": "kHP2SoTbPxA" },
  { "title": "S4 28 Limitless Mind", "videoId": "a8PVLiJf7GA" },
  { "title": "S4 27 The Art of Seduction Power and Persuasion Through History", "videoId": "ge--wWQxtH8" },
  { "title": "S4 26 Never Split the Difference Negotiation Tactics", "videoId": "lxDwIuYwGMM" },
  { "title": "S4 25 25 Need-to-Know MBA Models", "videoId": "CqzCNdQFwnc" },
  { "title": "S4 24 Everything Happens for a Reason - And Other Lies I've Loved", "videoId": "P3VOipr3iuU" },
  { "title": "S4 23 Authentic Happiness Foundations of Positive Psychology", "videoId": "960vMUsymE8" },
  { "title": "S4 22 Laziness Does Not Exist", "videoId": "y4nmKgtoc90" },
  { "title": "S4 21 21 Lessons for the 21st Century by Yuval Noah Harari", "videoId": "TBqbHlKWggw" },
  { "title": "S4 20 Critical Thinking An Introduction to Reasoning Well", "videoId": "DFLukI7FxX8" },
  { "title": "S4 10 Finish What You Start The Art of Following Through", "videoId": "I41CbiVzkto" },
  { "title": "S4 09 Time Management 10 Habits of Successful People To Manage Time", "videoId": "f5uHjEfsuG4" },
  { "title": "S4 08 80 20 Your Life Maximize Results with Minimal Effort", "videoId": "2eC_BjMuEIo" },
  { "title": "S4 07 The Now Habit at Work - Perform Optimally, Maintain Focus", "videoId": "71J_oQdb5So" },
  { "title": "S4 06 Mind Management, Not Time Management - Productivity When Creativity Matters", "videoId": "M1pnX7rvxYk" },
  { "title": "S4 05 Do it Now Effective Time Management and Productivity", "videoId": "2a4Y6_Z9ub4" },
  { "title": "S4 04 Do Hard Things Developing True Toughness", "videoId": "Fy1JC7hjqGo" },
  { "title": "S4 03 Do the Hard Things First Master Procrastination and Difficult Work", "videoId": "LHOd_3iOTrA" },
  { "title": "S4 02 Do It Tomorrow and Other Secrets of Time Management", "videoId": "G7bxA0LOj78" },
  { "title": "S4 01 The Time Paradox - Using the New Psychology of Time to Your Advantage", "videoId": "KNBHrUWmmyA" }
];

// Helper to extract S4 Index from title
function getIndex(title) {
  const m = title.match(/S4\s+(\d+)/);
  if (m) return "S4-" + m[1].padStart(2, '0');
  return null;
}

const finalS4 = [];
const startId = 497;
let currentId = startId;

// Process all indices S4-01 to S4-130
for (let i = 1; i <= 130; i++) {
  const index = "S4-" + String(i).padStart(2, '0');
  const tInfo = transcribed[index];
  
  if (!tInfo) {
    console.warn(`Missing transcription for ${index}`);
    continue;
  }

  // Find corresponding YouTube video
  const ytInfo = youtubeScraped.find(y => getIndex(y.title) === index);
  
  finalS4.push({
    id: `book_${currentId++}`,
    code: index,
    title_cn: "", // To be filled by batch search
    title_en: tInfo.en,
    playlist: "Book TALK - DeepDive Podcast S4",
    youtube_url: ytInfo ? `https://www.youtube.com/watch?v=${ytInfo.videoId}` : "",
    video_id: ytInfo ? ytInfo.videoId : "",
    video_title: ytInfo ? ytInfo.title : "",
    tags: ["S4"],
    description: "",
    author: tInfo.author,
    author_en: tInfo.author,
    original_language: "en", // Most are English originals
    isbn_zh: "",
    isbn_en: ""
  });
}

fs.writeFileSync('scripts/BChecker/s4_reconciled.json', JSON.stringify(finalS4, null, 2), 'utf8');
console.log(`Successfully reconciled ${finalS4.length} books. Output: scripts/BChecker/s4_reconciled.json`);
