const s4Data = [
  { index: "S4-01", title_en: "The Time Paradox", author: "Philip Zimbardo" },
  { index: "S4-02", title_en: "Do It Tomorrow", author: "Mark Forster" },
  { index: "S4-03", title_en: "Do the Hard Things First", author: "Scott Allan" },
  { index: "S4-04", title_en: "Do Hard Things", author: "Steve Magness" },
  { index: "S4-05", title_en: "Effective Time Management and Productivity", author: "Tracy Weaver" },
  { index: "S4-06", title_en: "Mind Management, Not Time Management", author: "David Kadavy" },
  { index: "S4-07", title_en: "The Now Habit at Work: Efficiency, Balance, and Focus", author: "Neil Fiore" },
  { index: "S4-08", title_en: "80/20 Your Life: Maximize Results with Minimal Effort", author: "Damon Zahariades" },
  { index: "S4-09", title_en: "Time Management", author: "Geoffrey Lucas" },
  { index: "S4-10", title_en: "Finish What You Start: The Art of Following Through", author: "Peter Hollins" },
  { index: "S4-11", title_en: "Betting on You", author: "Laurie Ruettimann" },
  { index: "S4-12", title_en: "HBR Work Smart Collection", author: "HBR" },
  { index: "S4-13", title_en: "Great by Choice", author: "Jim Collins" },
  { index: "S4-14", title_en: "Nobody Cares About Your Career", author: "Erika Ayers Badan" },
  { index: "S4-15", title_en: "Peak Performance", author: "Brad Stulberg & Steve Magness" },
  { index: "S4-16", title_en: "Peak Performance: Stress, Rest, and Sustainable Success", author: "Fitness Academy" },
  { index: "S4-17", title_en: "Smarter Not Harder: Biohacks for Effortless Energy and Performance", author: "Dave Asprey" },
  { index: "S4-18", title_en: "It Begins with You: Relationships, Patterns, and Healing", author: "Jillian Turecki" },
  { index: "S4-19", title_en: "The Gift of Fear", author: "Gavin De Becker" },
  { index: "S4-20", title_en: "Critical Thinking: The Basics of Good Reasoning", author: "Jamie Carlin Watson" },
  { index: "S4-21", title_en: "21 Lessons for the 21st Century", author: "Yuval Noah Harari" },
  { index: "S4-22", title_en: "Laziness Does Not Exist", author: "Devon Price" },
  { index: "S4-23", title_en: "Authentic Happiness", author: "Martin E. P. Seligman" },
  { index: "S4-24", title_en: "Everything Happens for a Reason", author: "Kate Bowler" },
  { index: "S4-25", title_en: "25 Need-to-Know MBA Models", author: "Ken Mark" },
  { index: "S4-26", title_en: "Never Split the Difference", author: "Chris Voss" },
  { index: "S4-27", title_en: "The Art of Seduction", author: "Robert Greene" },
  { index: "S4-28", title_en: "Limitless Mind", author: "Jo Boaler" },
  { index: "S4-29", title_en: "Intelligence: A Very Short Introduction", author: "Ian J. Deary" },
  { index: "S4-30", title_en: "Blue Ocean Strategy", author: "W. Chan Kim" },
  { index: "S4-31", title_en: "The Beginning of Infinity", author: "David Deutsch" },
  { index: "S4-32", title_en: "Building a Second Brain", author: "Tiago Forte" },
  { index: "S4-33", title_en: "The Achievement Habit", author: "Bernard Roth" },
  { index: "S4-34", title_en: "Story 10x: Turn the Impossible Into the Inevitable", author: "Michael Margolis" },
  { index: "S4-35", title_en: "Cultures of Growth", author: "Mary C. Murphy" },
  { index: "S4-36", title_en: "High Road Leadership", author: "John C. Maxwell" },
  { index: "S4-37", title_en: "Maxwell Leadership Bible", author: "John C. Maxwell" },
  { index: "S4-38", title_en: "The 10X Rule", author: "Grant Cardone" },
  { index: "S4-39", title_en: "Good Strategy/Bad Strategy", author: "Richard Rumelt" },
  { index: "S4-40", title_en: "Never Eat Alone", author: "Keith Ferrazzi" },
  { index: "S4-41", title_en: "The Simple Path to Wealth", author: "JL Collins" },
  { index: "S4-42", title_en: "Be a Millionaire Next Year", author: "Michael R. Berg" },
  { index: "S4-43", title_en: "Financial Joy 2.0", author: "Sean Seah" },
  { index: "S4-44", title_en: "Just Keep Buying", author: "Nick Maggiulli" },
  { index: "S4-45", title_en: "You Deserve to Be Rich", author: "Rashad Bilal" },
  { index: "S4-46", title_en: "The Psychology of Money", author: "Morgan Housel" },
  { index: "S4-47", title_en: "Why Motivating People Doesn't Work", author: "Susan Fowler" },
  { index: "S4-48", title_en: "Co-Active Leadership", author: "Karen Kimsey-House" },
  { index: "S4-49", title_en: "Exactly What to Say", author: "Phil M Jones" },
  { index: "S4-50", title_en: "Trillion Dollar Coach", author: "Eric Schmidt" },
  { index: "S4-51", title_en: "Servant Leadership", author: "Larry W. Boone" },
  { index: "S4-52", title_en: "Success 101", author: "John C. Maxwell" },
  { index: "S4-53", title_en: "Noise: A Flaw in Human Judgment", author: "Daniel Kahneman" },
  { index: "S4-54", title_en: "Predictably Irrational", author: "Dan Ariely" },
  { index: "S4-55", title_en: "Poor Numbers", author: "Morten Jerven" },
  { index: "S4-56", title_en: "The CEO Test", author: "Adam Bryant" },
  { index: "S4-57", title_en: "The Art of Work", author: "Jeff Goins" },
  { index: "S4-58", title_en: "The New One Minute Manager", author: "Ken Blanchard" },
  { index: "S4-59", title_en: "Call Sign Chaos", author: "Jim Mattis" },
  { index: "S4-60", title_en: "The Leap to Leader", author: "Adam Bryant" },
  { index: "S4-61", title_en: "Leaders Eat Last", author: "Simon Sinek" },
  { index: "S4-62", title_en: "Developing the Leader Within You", author: "John C. Maxwell" },
  { index: "S4-63", title_en: "Switch On Your Brain", author: "Dr. Caroline Leaf" },
  { index: "S4-64", title_en: "The Book of Joy", author: "Dalai Lama" },
  { index: "S4-65", title_en: "The Fun Habit", author: "Mike Rucker" },
  { index: "S4-66", title_en: "The Food-Mood Solution", author: "Jack Challem" },
  { index: "S4-67", title_en: "Lost Connections", author: "Johann Hari" },
  { index: "S4-68", title_en: "Lighter", author: "Yung Pueblo" },
  { index: "S4-69", title_en: "Get Out of My Head", author: "Meredith Arthur" },
  { index: "S4-70", title_en: "The Happiness Hypothesis", author: "Jonathan Haidt" },
  { index: "S4-71", title_en: "Master Your Beliefs", author: "Thibaut Meurisse" },
  { index: "S4-72", title_en: "Master Your Destiny", author: "Thibaut Meurisse" },
  { index: "S4-73", title_en: "Master Your Emotions", author: "Thibaut Meurisse" },
  { index: "S4-74", title_en: "Master Your Learning", author: "Thibaut Meurisse" },
  { index: "S4-75", title_en: "Master Your Thinking", author: "Thibaut Meurisse" },
  { index: "S4-76", title_en: "Dopamine Detox", author: "Thibaut Meurisse" },
  { index: "S4-77", title_en: "Mental Toughness", author: "Annette Tower" },
  { index: "S4-78", title_en: "Mind Map Mastery", author: "Tony Buzan" },
  { index: "S4-79", title_en: "Mind Your Mindset", author: "Michael Hyatt" },
  { index: "S4-80", title_en: "Moonwalking with Einstein", author: "Joshua Foer" },
  { index: "S4-81", title_en: "The Book of Minds", author: "Philip Ball" },
  { index: "S4-82", title_en: "Frames of Mind", author: "Howard Gardner" },
  { index: "S4-83", title_en: "How to Remember Anything", author: "Dean Vaughn" },
  { index: "S4-84", title_en: "Make It Stick", author: "Peter C. Brown" },
  { index: "S4-85", title_en: "Mind Magic", author: "James R. Doty" },
  { index: "S4-86", title_en: "Outsmart Your Brain", author: "Daniel T. Willingham" },
  { index: "S4-87", title_en: "The Confident Mind", author: "Dr. Nate Zinsser" },
  { index: "S4-88", title_en: "The Extended Mind", author: "Annie Murphy Paul" },
  { index: "S4-89", title_en: "The Power of Discipline", author: "Daniel Walter" },
  { index: "S4-90", title_en: "The Power of Fun", author: "Catherine Price" },
  { index: "S4-91", title_en: "The Power of Your Potential", author: "John C. Maxwell" },
  { index: "S4-92", title_en: "The Power of Your Subconscious Mind", author: "Joseph Murphy" },
  { index: "S4-93", title_en: "Quiet: The Power of Introverts", author: "Susan Cain" },
  { index: "S4-94", title_en: "The Art of Quiet Influence", author: "Jocelyn Davis" },
  { index: "S4-95", title_en: "The Secret Lives of Introverts", author: "Jenn Granneman" },
  { index: "S4-96", title_en: "Winning the War in Your Mind", author: "Craig Groeschel" },
  { index: "S4-97", title_en: "Make It Clear", author: "Patrick Henry Winston" },
  { index: "S4-98", title_en: "The Skill Code", author: "Matt Beane" },
  { index: "S4-99", title_en: "Think Like a Rocket Scientist", author: "Ozan Varol" },
  { index: "S4-100", title_en: "Third Millennium Thinking", author: "Saul Perlmutter" },
  { index: "S4-101", title_en: "The Rational Optimist", author: "Matt Ridley" },
  { index: "S4-102", title_en: "The Science of Self-Learning", author: "Peter Hollins" },
  { index: "S4-103", title_en: "The Yes Brain", author: "Daniel J. Siegel" },
  { index: "S4-104", title_en: "The 16 Undeniable Laws of Communication", author: "John C. Maxwell" },
  { index: "S4-105", title_en: "You're Not Listening", author: "Kate Murphy" },
  { index: "S4-106", title_en: "No Ego", author: "Cy Wakeman" },
  { index: "S4-107", title_en: "The Psychology of Overeating", author: "Kima Cargill" },
  { index: "S4-108", title_en: "Becoming Supernatural", author: "Dr. Joe Dispenza" },
  { index: "S4-109", title_en: "Win at Work and Succeed at Life", author: "Michael Hyatt" },
  { index: "S4-110", title_en: "The Ten Equations That Rule the World", author: "David Sumpter" },
  { index: "S4-111", title_en: "World Order", author: "Henry Kissinger" },
  { index: "S4-112", title_en: "Digital Empires", author: "Anu Bradford" },
  { index: "S4-113", title_en: "Educated", author: "Tara Westover" },
  { index: "S4-114", title_en: "Raising Good Humans Every Day", author: "Hunter Clarke-Fields" },
  { index: "S4-115", title_en: "ADHD", author: "Paul H. Wender" },
  { index: "S4-116", title_en: "Exploratory Writing", author: "Alison Jones" },
  { index: "S4-117", title_en: "Moving On Doesn't Mean Letting Go", author: "Gina Moffa" },
  { index: "S4-118", title_en: "No Bad Parts", author: "Richard C. Schwartz" },
  { index: "S4-119", title_en: "The Mindful Way through Depression", author: "Mark Williams" },
  { index: "S4-120", title_en: "The Perfectionist's Guide to Losing Control", author: "Katherine Morgan Schafler" },
  { index: "S4-121", title_en: "What Happened to You", author: "Oprah Winfrey" },
  { index: "S4-122", title_en: "When Bad Thinking Happens to Good People", author: "Steven Nadler" },
  { index: "S4-123", title_en: "This Is Strategy", author: "Seth Godin" },
  { index: "S4-124", title_en: "The Hidden Life of Trees", author: "Peter Wohlleben" },
  { index: "S4-125", title_en: "The Laws of Human Nature", author: "Robert Greene" },
  { index: "S4-126", title_en: "How to Work with Complicated People", author: "Ryan Leak" },
  { index: "S4-127", title_en: "101 Creative Problem Solving Techniques", author: "James M. Higgins" },
  { index: "S4-128", title_en: "No-Drama Discipline", author: "Daniel J. Siegel" },
  { index: "S4-129", title_en: "I Used to Have a Plan_ But Life had other Ideas", author: "Alessandra Olanow" },
  { index: "S4-130", title_en: "Power and Progress", author: "Daron Acemoglu" }
];

console.log(JSON.stringify(s4Data, null, 2));
