import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext(null);

const translations = {
    zh: {
        siteTitle: '🌌 WeLearn 知識宇宙',
        siteSubtitle: '跨領域遊戲化智慧學習殿堂',
        search: '搜尋書籍、作者或星域關鍵字...',
        tags: '知識標籤',
        playlists: '精選修煉書單',
        all: '全部領域',
        play: '播放導讀',
        booksFound: '本書籍',
        showing: '顯示',
        outOf: '/',
        backToList: '返回書單',
        playEpisode: '播放影音',
        englishVersion: '英文版導讀',
        noBooks: '找不到符合條件的書籍',
        aboutAuthor: '關於作者',
        authorBio: '作者介紹',
        achievements: '主要成就',
        booksCollected: '收錄書籍',
        career: '專業領域',
        stats: '數據統計',
        back: '返回',
        viewProfile: '查看完整專頁',
        publishingInfo: '書籍出版資訊',
        originalLanguage: '原著語言',
        isbnEn: '英文版 ISBN-13',
        isbnZh: '中文版 ISBN-13',
        authorsList: '百大作者殿堂',
        booksByAuthor: '本站書籍',

        // 遊戲化相關字詞
        universePortal: '知識宇宙星系',
        questsCenter: '每日修煉大廳',
        achievementsHall: '成就勳章圖鑑',
        scholarProfile: '冒險者學者名片',
        serendipityPick: '滄海一粟 · 隨選好書',
        serendipityBtn: '滄海一粟',
        wisdomCapsule: '每日智慧靈感卡',
        checkIn: '每日打卡',
        checkedIn: '今日已完成修行',
        level: '等級',
        exp: '經驗值',
        streak: '天連勝',
        sparks: '靈感點數',
        markAsRead: '標記為已研讀',
        completedRead: '已完成研讀',
        addToBookmarks: '加入收藏',
        inBookmarks: '已收藏',
        scholarNotes: '研讀筆記與書摘',
        writeNotesPlaceholder: '記錄您的核心啟發、思維模型或行動清單...',
        saveNote: '儲存筆記',
        noteSaved: '筆記已儲存',
        crossUniverseSynapses: '跨星系知識共鳴 (Cross-Universe Synapses)',
        exploreRealm: '進入星域探索',
        openWebsite: '前往官方站點',
        dailyQuests: '今日修行任務',
        questCompleted: '已達成',
        claimCapsule: '領取今日靈感金句',
        levelUpTitle: '🎉 榮耀晉升！',
        newBadgeUnlocked: '🏆 獲得新成就勳章！',
        streakProtected: '連勝護盾生效中',
        buyFreeze: '兌換連勝護盾 (100 點)',
        exportData: '匯出學習進度',
        importData: '匯入進度備份',
        resetData: '重置所有進度',
        sharePassport: '分享學者成就名片',
        copied: '已複製到剪貼簿',
        realmsExplored: '星域探索度',
        booksReadCount: '已研讀書籍',
        totalNotesCount: '累積書摘筆記',

        // 學習科學與框架系統
        learningScience: '學習科學與框架',
        learningScienceSubtitle: '腦科學、記憶編碼、成長心態、思維模型與底層邏輯全景系統',
        scienceOverview: '全景概覽',
        dimensionsNav: '六大科學維度',
        mentalModelsNav: '心智模型速查庫',
        diagnosticNav: '學習模式診斷',
        closedLoopNav: '實踐閉環地圖',
        allDimensions: '全部維度',
        exploreBooks: '探索館藏關聯經典好書',
        viewBookDetail: '前往深度導讀',
        biologicalMechanisms: '神經生物與認知底層機制',
        cognitiveTraps: '常見無效陷阱與科學破解',
        actionProtocols: '科學落地行動方針',
        startDiagnostic: '開始 5 題學習體系體檢',
        retakeDiagnostic: '重新進行診斷評估',
        diagnosticResult: '您的學習系統診斷報告',
        overallScore: '總體學習力指數',
        dominantArchetype: '核心學習者原型',
        recommendedBooksForYou: '為您客製化的優先補強書單',
        searchFrameworkBooks: '在學習科學館藏中搜尋書名、作者或關鍵字...',
        filterByDimension: '依科學維度篩選',
        totalCuratedBooks: '本科學架構收錄核心書籍'
    },
    en: {
        siteTitle: '🌌 WeLearn Multiverse',
        siteSubtitle: 'Cross-Disciplinary Gamified Knowledge Nexus',
        search: 'Search books, authors, or topics...',
        tags: 'Knowledge Tags',
        playlists: 'Curated Study Tracks',
        all: 'All Domains',
        play: 'Play Summary',
        booksFound: 'books',
        showing: 'Showing',
        outOf: '/',
        backToList: 'Back to list',
        playEpisode: 'Play',
        englishVersion: 'English Version',
        noBooks: 'No books found',
        aboutAuthor: 'About Author',
        authorBio: 'Author Biography',
        achievements: 'Key Achievements',
        booksCollected: 'Curated Books',
        career: 'Career',
        stats: 'Statistics',
        back: 'Back',
        viewProfile: 'View Profile',
        publishingInfo: 'Publishing Information',
        originalLanguage: 'Original Language',
        isbnEn: 'English ISBN-13',
        isbnZh: 'Chinese ISBN-13',
        authorsList: 'Authors Hall',
        booksByAuthor: 'Books in Site',

        // Gamification terms
        universePortal: 'Cosmic Realms Hub',
        questsCenter: 'Daily Quests Hall',
        achievementsHall: 'Achievements Showcase',
        scholarProfile: 'Scholar Passport',
        serendipityPick: 'A Drop in the Ocean · Random Pick',
        serendipityBtn: 'A Drop in the Ocean',
        wisdomCapsule: 'Daily Inspiration Card',
        checkIn: 'Daily Check-in',
        checkedIn: 'Practiced Today',
        level: 'Level',
        exp: 'EXP',
        streak: 'Day Streak',
        sparks: 'Wisdom Sparks',
        markAsRead: 'Mark as Completed',
        completedRead: 'Study Completed',
        addToBookmarks: 'Add Bookmark',
        inBookmarks: 'Bookmarked',
        scholarNotes: 'Scholar Notes & Quotes',
        writeNotesPlaceholder: 'Record your core takeaways, mental models, or action items...',
        saveNote: 'Save Note',
        noteSaved: 'Note Saved',
        crossUniverseSynapses: 'Cross-Universe Synapses',
        exploreRealm: 'Explore Realm',
        openWebsite: 'Open Website',
        dailyQuests: 'Daily Quests',
        questCompleted: 'Completed',
        claimCapsule: 'Claim Daily Inspiration',
        levelUpTitle: '🎉 Level Up Rank Promotion!',
        newBadgeUnlocked: '🏆 New Badge Unlocked!',
        streakProtected: 'Streak Freeze Active',
        buyFreeze: 'Buy Streak Freeze (100 Sparks)',
        exportData: 'Export Scholar Data',
        importData: 'Import Backup',
        resetData: 'Reset Progress',
        sharePassport: 'Share Scholar Passport',
        copied: 'Copied to Clipboard',
        realmsExplored: 'Realms Explored',
        booksReadCount: 'Books Studied',
        totalNotesCount: 'Notes Taken',

        // Learning Science System
        learningScience: 'Science of Learning & Framework',
        learningScienceSubtitle: 'Neuroscience, Memory Encoding, Mindset, Mental Models & Closed-Loop Systems',
        scienceOverview: 'Overview',
        dimensionsNav: '6 Core Dimensions',
        mentalModelsNav: 'Mental Models Library',
        diagnosticNav: 'Diagnostic Assessment',
        closedLoopNav: 'Closed-Loop Workflow',
        allDimensions: 'All Dimensions',
        exploreBooks: 'Curated Books in Codex',
        viewBookDetail: 'View Book Deep Dive',
        biologicalMechanisms: 'Biological & Cognitive Mechanisms',
        cognitiveTraps: 'Cognitive Illusions & Solutions',
        actionProtocols: 'Actionable Protocols',
        startDiagnostic: 'Start 5-Question Diagnostic',
        retakeDiagnostic: 'Retake Diagnostic',
        diagnosticResult: 'Your Learning System Diagnostic Report',
        overallScore: 'Overall Learning Index',
        dominantArchetype: 'Dominant Learner Archetype',
        recommendedBooksForYou: 'Personalized Curated Reading Recommendations',
        searchFrameworkBooks: 'Search book title, author, or keyword in learning codex...',
        filterByDimension: 'Filter by Dimension',
        totalCuratedBooks: 'Core Curated Books in Framework'
    },
};

const tagTranslations = {
    '人文與科學': 'Humanities & Science',
    '個人成長': 'Personal Growth',
    '心理學': 'Psychology',
    '商業': 'Business',
    '投資理財': 'Finance',
    '健康與生活': 'Health & Life',
    '文學與故事': 'Literature',
    '科技': 'Technology',
    '社會與文化': 'Society & Culture',
    '職場工作': 'Career',
    '哲學思維': 'Philosophy',
    '溝通表達': 'Communication',
    '教育學習': 'Education',
    '歷史': 'History',
    '親子教養': 'Parenting',
    '心智與思維': 'Mindset',
    '自我認識': 'Self-awareness',
    '環境閱讀': 'Environment',
    '飲食健康': 'Food & Health',
    '行旅閱讀': 'Travel',
    '創業': 'Entrepreneurship',
    '設計': 'Design',
    '運動健身': 'Sports & Fitness',
    '管理領導': 'Leadership',
    '音樂': 'Music',
    '電影': 'Film',
    '政治': 'Politics',
    '法律': 'Law',
    '數學': 'Math',
    '物理': 'Physics',
    '生物': 'Biology',
    '工作效率': 'Productivity',
    '思考技術': 'Critical Thinking',
    '未來趨勢': 'Future Trends',
    '心靈平靜': 'Mindfulness',
    '創業經營': 'Management',
    '溝通談判': 'Negotiation',
    '閱讀學習': 'Learning',
    '財富自由': 'Financial Freedom',
    '信仰': 'Faith & Theology',
    '靈修': 'Spiritual Devotion',
    '生命智慧': 'Life Wisdom',
    '道德倫理': 'Ethics',
    '系統架構': 'System Architecture',
    '軟體工程': 'Software Engineering',
    '雲端': 'Cloud Native',
    '古文經典': 'Ancient Classics',
    '語言學習': 'Language Learning',
    '東南亞文化': 'Southeast Asian Culture',
    '越南語': 'Vietnamese',
    '印尼語': 'Indonesian',
    '千島文化': 'Archipelago Culture',
    '海外視野': 'Global Perspectives',
    '商務拓展': 'Business Expansion'
};

export function LanguageProvider({ children }) {
    const [language, setLanguage] = useState('zh');

    const t = (key) => translations[language]?.[key] || translations['zh']?.[key] || key;
    const toggleLanguage = () => setLanguage(l => l === 'zh' ? 'en' : 'zh');
    const translateTag = (tag) => language === 'en' ? (tagTranslations[tag] || tag) : tag;

    return (
        <LanguageContext.Provider value={{ language, t, toggleLanguage, translateTag }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    return useContext(LanguageContext);
}
